AWSTemplateFormatVersion: "2010-09-09"
Description: >
    Test template to create EC2 Instance using CloudFormation
Parameters:
    InstanceTypeParameter:
        Description: EC2 instance type
        Type: String
        Default: t2.micro
        AllowedValues:
            - t2.micro
            - m1.small
            - m1.large
        ConstraintDescription: Enter Instance Type. Default is t2.micro.
    KeyName:
        Description: Name of an existing EC2 KeyPair for SSH access.
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: Must be the name of an existing EC2 KeyPair
    SSHLocation:
        Description: The IP address range that can be used to SSH to the EC2 instance
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
        ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
    RegionMap:
        us-east-1:
            HVM64: ami-0ff8a91507f77f867
        us-east-2:
            HVM64: ami-0b59bfac6be064b78
        us-west-1:
            HVM64: ami-0bdb828fd58c52235
        us-west-2:
            HVM64: ami-a0cfeed8
Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Metadata:
            Comment: Install Apache, PHP
            AWS::CloudFormation::Init:
                config:
                    packages:
                        yum:
                            httpd: []
                            mariadb: []
                            php: []
                    services:
                        sysvinit:
                            httpd:
                                enabled: true
                                ensureRunning: true
                            mariadb:
                                enabled: true
                                ensureRunning: true
        Properties:
            ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', 'HVM64']
            InstanceType: !Ref "InstanceTypeParameter"
            KeyName: !Ref KeyName
            SecurityGroups: ["penny-test_SG_Ohio"]
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash -xe
                    yum update -y aws-cfn-bootstrap
                    /opt/aws/bin/cfn-init -v --stack $(AWS::StackId) --resource EC2Instance --region $(AWS::Region)
Outputs:
    InstanceID:
        Description: The EC2 instance ID
        Value: !Ref EC2Instance
    PublicIP:
        Description: EC2 public IP
        Value: !GetAtt EC2Instance.PublicIp